PAYMENT_INTEGRATION_SERVICE_BASE_PATH: "http://payment-integration-service.preprod:8080"
RECONCILIATION_SERVICE_BASE_PATH: "http://reconciliation-service.preprod:8080"
POCKET_SERVICE_BASE_PATH: "http://pocket-service.preprod:8080"
TAX_SERVICE_BASE_PATH: "http://tax-service.preprod:8080"
OPERATION_SERVICE_BASE_PATH: "http://operations-service.preprod:8080"
SMTP_HOST: "email-smtp.ap-southeast-1.amazonaws.com"
SMPT_PORT: "587"
SMTP_USERNAME: "AKIASWI3QINMLQV5VPP7"
SMTP_FROMEMAIL: "pavan.chinnamanthur@publicissapient.com"
SMTP_TOEMAIL: "pavan.chinnamanthur@publicissapient.com"
AMAZON_S3_BUCKET_NAME: "rider-internal-content-preprod"
