PAYMENT_INTEGRATION_SERVICE_BASE_PATH: "http://payment-integration-service.prod:8080"
RECONCILIATION_SERVICE_BASE_PATH: "http://reconciliation-service.prod:8080"
POCKET_SERVICE_BASE_PATH: "http://pocket-service.prod:8080"
TAX_SERVICE_BASE_PATH: "http://tax-service.prod:8080"
OPERATION_SERVICE_BASE_PATH: "http://operations-service.prod:8080"
SMTP_HOST: "email-smtp.ap-southeast-1.amazonaws.com"
SMPT_PORT: "587"
SMTP_USERNAME: "AKIAVRZWB2B7CTXYQLRP"
SMTP_FROMEMAIL: "no-reply-robinhoodrider@robinhood.in.th"
SMTP_TOEMAIL: "operation@robinhood.in.th"
AMAZON_S3_BUCKET_NAME: "rider-internal-content-prod"
