PAYMENT_INTEGRATION_SERVICE_BASE_PATH: "http://payment-integration-service.dev:8080"
RECONCILIATION_SERVICE_BASE_PATH: "http://reconciliation-service.dev:8080"
POCKET_SERVICE_BASE_PATH: "http://pocket-service.dev:8080"
TAX_SERVICE_BASE_PATH: "http://tax-service.dev:8080"
OPERATION_SERVICE_BASE_PATH: "http://operations-service.dev:8080"
SMTP_HOST: "email-smtp.ap-southeast-1.amazonaws.com"
SMPT_PORT: "587"
SMTP_USERNAME: "AKIASWI3QINMLQV5VPP7"
SMTP_FROMEMAIL: "rohit.sharma@publicissapient.com"
SMTP_TOEMAIL: "rohit.sharma@publicissapient.com"
AMAZON_S3_BUCKET_NAME: "rider-internal-content-dev"
COMPANY: "SCB"
PROJECT_NAME: "rider"
DIST_TRACER_ENDPOINT: "http://jaeger-operator-jaeger-collector.default:14268/api/traces"
