---
# Source: environment/templates/devops-config/deployment/deployment-vars-{{env}}.yml
# This file was generated at  using generator Version: 

DEPLOYMENT:
    ENV: preprod
    NAMESPACE: preprod
    CONFIG_FILES:
        - "src/main/resources/config/settlement-service.default.yaml"
        - "src/main/resources/config/settlement-service.preprod.yaml"

APP:
    REPLICA: 2
    HPA:
      ENABLED: 1
      MIN_REPLICA: 1
      MAX_REPLICA: 3
      CPU_UTILIZATION: 65
      MEMORY_UTILIZATION: 80
    CONTAINER:
      MEMORY:
        REQUEST: 1Gi
        LIMIT: 8Gi
      CPU:
        REQUEST: 0.5
        LIMIT: 4
    ENVIRONMENT:
      - KEY: logs.Dir
        VALUE: "/apps/logs/preprod/settlement-service/"
